# Generated by Django 4.2.30 on 2026-05-12 10:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_date', models.DateField(verbose_name='Session Date')),
                ('duration_minutes', models.IntegerField(default=0, verbose_name='Duration (minutes)')),
                ('activity_type', models.CharField(choices=[('quiz', 'Quiz'), ('simplifier', 'Note Simplification'), ('planner', 'Study Planner'), ('notes', 'Note Reading')], max_length=20, verbose_name='Activity Type')),
            ],
            options={
                'verbose_name': 'Study Session',
                'verbose_name_plural': 'Study Sessions',
                'ordering': ['-session_date'],
            },
        ),
        migrations.CreateModel(
            name='TeacherAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('score_drop', 'Score Drop'), ('inactivity', 'Inactivity'), ('struggling_topic', 'Struggling Topic')], max_length=20, verbose_name='Alert Type')),
                ('message', models.TextField(help_text='Human-readable description of what triggered this alert', verbose_name='Alert Message')),
                ('is_read', models.BooleanField(default=False, verbose_name='Read by Teacher')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Teacher Alert',
                'verbose_name_plural': 'Teacher Alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyProgressSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('week_start_date', models.DateField(help_text='Always a Monday', verbose_name='Week Start Date')),
                ('average_quiz_score', models.FloatField(default=0.0, verbose_name='Average Quiz Score (%)')),
                ('total_study_minutes', models.IntegerField(default=0, verbose_name='Total Study Minutes')),
                ('notes_created_count', models.IntegerField(default=0, verbose_name='Notes Created')),
                ('quizzes_completed_count', models.IntegerField(default=0, verbose_name='Quizzes Completed')),
            ],
            options={
                'verbose_name': 'Weekly Progress Snapshot',
                'verbose_name_plural': 'Weekly Progress Snapshots',
                'ordering': ['-week_start_date'],
            },
        ),
    ]
