# Generated by Django 4.2.30 on 2026-05-14 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('progress', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyprogresssnapshot',
            name='english_score',
            field=models.FloatField(default=0.0, verbose_name='English Score (%)'),
        ),
        migrations.AddField(
            model_name='weeklyprogresssnapshot',
            name='kinyarwanda_score',
            field=models.FloatField(default=0.0, verbose_name='Kinyarwanda Score (%)'),
        ),
        migrations.AddField(
            model_name='weeklyprogresssnapshot',
            name='math_score',
            field=models.FloatField(default=0.0, verbose_name='Math Score (%)'),
        ),
        migrations.AddField(
            model_name='weeklyprogresssnapshot',
            name='science_score',
            field=models.FloatField(default=0.0, verbose_name='Science Score (%)'),
        ),
        migrations.AddField(
            model_name='weeklyprogresssnapshot',
            name='social_score',
            field=models.FloatField(default=0.0, verbose_name='Social Score (%)'),
        ),
        migrations.AlterField(
            model_name='teacheralert',
            name='message',
            field=models.TextField(verbose_name='Alert Message'),
        ),
        migrations.CreateModel(
            name='SubjectMastery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(choices=[('Math', 'Math'), ('English', 'English'), ('Science', 'Science'), ('Kinyarwanda', 'Kinyarwanda'), ('Social', 'Social')], max_length=20, verbose_name='Subject')),
                ('value', models.FloatField(default=0.0, help_text='0–100 mastery percentage for this subject', verbose_name='Mastery (%)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_masteries', to=settings.AUTH_USER_MODEL, verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Subject Mastery',
                'verbose_name_plural': 'Subject Masteries',
                'ordering': ['subject'],
                'unique_together': {('student', 'subject')},
            },
        ),
    ]
