# Generated by Django 4.2.30 on 2026-05-12 10:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioGeneration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('audio_file', models.FileField(blank=True, help_text='Generated MP3 file — available when status is completed', null=True, upload_to='notes/audio/', verbose_name='Audio File')),
                ('language', models.CharField(default='english', max_length=20, verbose_name='Audio Language')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=15, verbose_name='Generation Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Audio Generation',
                'verbose_name_plural': 'Audio Generations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SimplifiedNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('simplified_text', models.TextField(verbose_name='Simplified Text')),
                ('glossary', models.JSONField(default=list, help_text='List of difficult terms with simple definitions', verbose_name='Key Terms Glossary')),
                ('reading_level', models.CharField(choices=[('simple', 'Simple'), ('intermediate', 'Intermediate')], default='simple', max_length=20, verbose_name='Reading Level')),
                ('ai_model_used', models.CharField(help_text='The AI model that generated this simplification', max_length=100, verbose_name='AI Model')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Simplified Note',
                'verbose_name_plural': 'Simplified Notes',
            },
        ),
        migrations.CreateModel(
            name='StudentNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Note Title')),
                ('text_content', models.TextField(blank=True, help_text='Text pasted directly by the student', null=True, verbose_name='Pasted Text')),
                ('uploaded_file', models.FileField(blank=True, help_text='Document uploaded by the student (PDF, DOCX, TXT)', null=True, upload_to='notes/uploads/', verbose_name='Uploaded File')),
                ('language', models.CharField(default='english', max_length=20, verbose_name='Note Language')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Student Note',
                'verbose_name_plural': 'Student Notes',
                'ordering': ['-created_at'],
            },
        ),
    ]
