# Generated by Django 4.2.30 on 2026-05-12 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('simplifier', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studentnote',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL, verbose_name='Student'),
        ),
        migrations.AddField(
            model_name='simplifiednote',
            name='original_note',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='simplified_version', to='simplifier.studentnote', verbose_name='Original Note'),
        ),
        migrations.AddField(
            model_name='audiogeneration',
            name='simplified_note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_generations', to='simplifier.simplifiednote', verbose_name='Simplified Note'),
        ),
    ]
