# Generated by Django 4.2.30 on 2026-05-12 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_feature', models.CharField(help_text='Which app triggered this call: simplifier, quizzes, planner, career', max_length=50, verbose_name='Source Feature')),
                ('ai_model_name', models.CharField(help_text='e.g. claude-sonnet-4-20250514', max_length=100, verbose_name='AI Model Name')),
                ('call_status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], max_length=10, verbose_name='Call Status')),
                ('error_message', models.TextField(blank=True, default='', help_text='Populated only when call_status is failed', verbose_name='Error Message')),
                ('response_time_ms', models.IntegerField(default=0, help_text='How long the AI API call took in milliseconds', verbose_name='Response Time (ms)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'AI Request Log',
                'verbose_name_plural': 'AI Request Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
