"""
planner/models.py
Models for AI-generated personalised study plans, upcoming exams, and daily study blocks.
"""
import uuid
from django.db import models
from django.conf import settings


class StudyPlan(models.Model):
    """
    A student's personalised study plan generated by Claude AI.
    Only one plan can be active per student at a time.
    Creating a new plan automatically deactivates the previous one.
    """
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    student = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="study_plans",
        verbose_name="Student",
    )
    is_active = models.BooleanField(
        default=True,
        verbose_name="Is Active",
        help_text="Only one active plan allowed per student",
    )
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = "Study Plan"
        verbose_name_plural = "Study Plans"
        ordering = ["-created_at"]

    def __str__(self):
        status = "Active" if self.is_active else "Inactive"
        return f"{self.student.full_name}'s Study Plan ({status})"


class UpcomingExam(models.Model):
    """
    An exam the student needs to prepare for, linked to their study plan.
    Priority level determines how much study time the AI allocates to this subject.
    """

    class Priority(models.IntegerChoices):
        HIGH = 1, "High Priority"      # nearest or most important exam
        MEDIUM = 2, "Medium Priority"
        LOW = 3, "Low Priority"

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    study_plan = models.ForeignKey(
        StudyPlan,
        on_delete=models.CASCADE,
        related_name="upcoming_exams",
        verbose_name="Study Plan",
    )
    subject_name = models.CharField(
        max_length=255,
        verbose_name="Subject Name",
    )
    exam_date = models.DateField(verbose_name="Exam Date")
    priority_level = models.IntegerField(
        choices=Priority.choices,
        default=Priority.MEDIUM,
        verbose_name="Priority Level",
    )

    class Meta:
        verbose_name = "Upcoming Exam"
        verbose_name_plural = "Upcoming Exams"
        ordering = ["exam_date"]

    def __str__(self):
        return f"{self.subject_name} — {self.exam_date} ({self.get_priority_level_display()})"


class DailyStudyBlock(models.Model):
    """
    A single time-blocked study session within a study plan.
    Generated by Claude AI and can be auto-rescheduled when the student falls behind.
    Each block has a specific subject and a concrete study goal.
    """
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    study_plan = models.ForeignKey(
        StudyPlan,
        on_delete=models.CASCADE,
        related_name="daily_blocks",
        verbose_name="Study Plan",
    )
    scheduled_date = models.DateField(verbose_name="Scheduled Date")
    start_time = models.TimeField(verbose_name="Start Time")
    end_time = models.TimeField(verbose_name="End Time")
    subject_name = models.CharField(max_length=255, verbose_name="Subject")
    study_goal = models.TextField(
        verbose_name="Study Goal",
        help_text="Specific task the student should complete in this block",
    )
    is_completed = models.BooleanField(
        default=False,
        verbose_name="Completed",
    )
    was_rescheduled_by_ai = models.BooleanField(
        default=False,
        verbose_name="AI Rescheduled",
        help_text="True if this block was regenerated after a missed session",
    )

    class Meta:
        verbose_name = "Daily Study Block"
        verbose_name_plural = "Daily Study Blocks"
        ordering = ["scheduled_date", "start_time"]

    def __str__(self):
        return f"{self.scheduled_date} {self.start_time}–{self.end_time} | {self.subject_name}"
