# Generated by Django 4.2.30 on 2026-05-12 10:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CareerAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_answers', models.JSONField(help_text="Student's answers to all 8 career assessment questions", verbose_name='Assessment Answers')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Career Assessment',
                'verbose_name_plural': 'Career Assessments',
            },
        ),
        migrations.CreateModel(
            name='CareerRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('career_title', models.CharField(help_text='e.g. Software Engineer, Medical Doctor', max_length=255, verbose_name='Career Title')),
                ('career_description', models.TextField(verbose_name='Career Description')),
                ('required_subjects', models.JSONField(default=list, verbose_name='Required Subjects')),
                ('african_universities', models.JSONField(default=list, help_text='Local universities where this career can be studied', verbose_name='African Universities')),
                ('match_score', models.FloatField(help_text="How well this career matches the student's profile (0–100)", verbose_name='Match Score (%)')),
                ('rank', models.IntegerField(help_text='1 = best match, 3 = third best match', verbose_name='Rank')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='career.careerassessment', verbose_name='Career Assessment')),
            ],
            options={
                'verbose_name': 'Career Recommendation',
                'verbose_name_plural': 'Career Recommendations',
                'ordering': ['rank'],
            },
        ),
    ]
