# Generated by Django 4.2.30 on 2026-05-13 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Short description of the assignment shown on the dashboard.', max_length=255, verbose_name='Title')),
                ('subject', models.CharField(help_text='e.g. Mathematics, English, Science.', max_length=100, verbose_name='Subject')),
                ('due', models.DateField(help_text='The date by which students must complete this assignment.', verbose_name='Due Date')),
                ('class_id', models.CharField(help_text="Identifier for the class this assignment targets. Matches the teacher's class_grade field (e.g. 'P6').", max_length=50, verbose_name='Class ID')),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('completed', 'Completed')], default='assigned', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(help_text='The teacher who created this assignment.', limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='created_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Assignment',
                'verbose_name_plural': 'Assignments',
                'ordering': ['due'],
            },
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('subject', models.CharField(max_length=100, verbose_name='Subject')),
                ('due', models.DateField(verbose_name='Due Date')),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('completed', 'Completed')], default='assigned', max_length=20, verbose_name='Status')),
                ('xp_reward', models.IntegerField(default=50, help_text='XP awarded to the student when they mark this homework as complete. Default is 50 XP per the frontend spec.', verbose_name='XP Reward')),
                ('completed_at', models.DateTimeField(blank=True, help_text='Timestamp set automatically when the student marks this as done.', null=True, verbose_name='Completed At')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(help_text='The teacher who assigned this homework.', limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_homework', to=settings.AUTH_USER_MODEL, verbose_name='Assigned By')),
                ('assignment', models.ForeignKey(blank=True, help_text='The assignment this homework was generated from. Null for homework created directly for an individual student.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='homework_items', to='homework.assignment', verbose_name='Source Assignment')),
                ('student', models.ForeignKey(help_text='The student this homework is assigned to.', limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='homework', to=settings.AUTH_USER_MODEL, verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Homework',
                'verbose_name_plural': 'Homework',
                'ordering': ['due'],
            },
        ),
    ]
