# Generated by Django 4.2.30 on 2026-05-12 10:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStudyBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_date', models.DateField(verbose_name='Scheduled Date')),
                ('start_time', models.TimeField(verbose_name='Start Time')),
                ('end_time', models.TimeField(verbose_name='End Time')),
                ('subject_name', models.CharField(max_length=255, verbose_name='Subject')),
                ('study_goal', models.TextField(help_text='Specific task the student should complete in this block', verbose_name='Study Goal')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Completed')),
                ('was_rescheduled_by_ai', models.BooleanField(default=False, help_text='True if this block was regenerated after a missed session', verbose_name='AI Rescheduled')),
            ],
            options={
                'verbose_name': 'Daily Study Block',
                'verbose_name_plural': 'Daily Study Blocks',
                'ordering': ['scheduled_date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='StudyPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, help_text='Only one active plan allowed per student', verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Study Plan',
                'verbose_name_plural': 'Study Plans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UpcomingExam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=255, verbose_name='Subject Name')),
                ('exam_date', models.DateField(verbose_name='Exam Date')),
                ('priority_level', models.IntegerField(choices=[(1, 'High Priority'), (2, 'Medium Priority'), (3, 'Low Priority')], default=2, verbose_name='Priority Level')),
                ('study_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upcoming_exams', to='planner.studyplan', verbose_name='Study Plan')),
            ],
            options={
                'verbose_name': 'Upcoming Exam',
                'verbose_name_plural': 'Upcoming Exams',
                'ordering': ['exam_date'],
            },
        ),
    ]
