# Generated by Django 4.2.30 on 2026-05-12 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyplan',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_plans', to=settings.AUTH_USER_MODEL, verbose_name='Student'),
        ),
        migrations.AddField(
            model_name='dailystudyblock',
            name='study_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_blocks', to='planner.studyplan', verbose_name='Study Plan'),
        ),
    ]
