# Generated by Django 4.2.30 on 2026-05-13 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('planner', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailystudyblock',
            name='is_completed',
            field=models.BooleanField(default=False, help_text='Set to True when the student marks this block as done.', verbose_name='Completed'),
        ),
        migrations.AlterField(
            model_name='dailystudyblock',
            name='study_goal',
            field=models.TextField(help_text='Specific task the student should complete during this block.', verbose_name='Study Goal'),
        ),
        migrations.AlterField(
            model_name='dailystudyblock',
            name='was_rescheduled_by_ai',
            field=models.BooleanField(default=False, help_text='True if this block was regenerated after a missed session.', verbose_name='AI Rescheduled'),
        ),
        migrations.AlterField(
            model_name='studyplan',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Only one active plan is allowed per student at a time.', verbose_name='Is Active'),
        ),
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID — matches the id stored in the frontend localStorage entry.', primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Short label shown on the calendar tile.', max_length=255, verbose_name='Title')),
                ('date', models.DateField(help_text='The date this event falls on — format YYYY-MM-DD.', verbose_name='Event Date')),
                ('color', models.CharField(choices=[('green', 'Green'), ('blue', 'Blue'), ('purple', 'Purple'), ('orange', 'Orange'), ('red', 'Red'), ('yellow', 'Yellow')], default='blue', help_text='Colour used to render the event tile on the frontend calendar.', max_length=10, verbose_name='Color')),
                ('type', models.CharField(choices=[('task', 'Task'), ('assignment', 'Assignment'), ('exam', 'Exam'), ('reminder', 'Reminder')], default='task', help_text='Controls the icon and badge shown on the frontend.', max_length=20, verbose_name='Event Type')),
                ('done', models.BooleanField(default=False, help_text='True when the student marks the event as completed.', verbose_name='Done')),
                ('mark', models.IntegerField(blank=True, help_text='Teacher-assigned grade for this event. Null until the teacher grades the submission.', null=True, verbose_name='Mark (0–100)')),
                ('due_notified', models.BooleanField(default=False, help_text='True once the frontend has shown a due-date notification for this event.', verbose_name='Due Notified')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(help_text='The student who owns this event.', on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to=settings.AUTH_USER_MODEL, verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Calendar Event',
                'verbose_name_plural': 'Calendar Events',
                'ordering': ['date'],
            },
        ),
    ]
