# Generated by Django 4.2.30 on 2026-05-12 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(help_text='Used as the login identifier', max_length=254, unique=True, verbose_name='Email Address')),
                ('full_name', models.CharField(max_length=255, verbose_name='Full Name')),
                ('role', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher')], default='student', max_length=10, verbose_name='Account Role')),
                ('preferred_language', models.CharField(choices=[('kinyarwanda', 'Kinyarwanda'), ('english', 'English'), ('french', 'French'), ('swahili', 'Swahili')], default='english', help_text='Language used for AI-generated content', max_length=20, verbose_name='Preferred Language')),
                ('learning_style', models.CharField(blank=True, choices=[('visual', 'Visual'), ('auditory', 'Auditory'), ('reading', 'Reading'), ('kinesthetic', 'Kinesthetic')], help_text='Set during onboarding — personalises AI content', max_length=20, null=True, verbose_name='Learning Style')),
                ('is_dyslexic', models.BooleanField(default=False, help_text='Enables dyslexia-friendly simplification and larger fonts', verbose_name='Has Dyslexia')),
                ('is_premium', models.BooleanField(default=False, help_text='Unlocks AI quizzes and career guidance features', verbose_name='Premium Account')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Date Joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='ClassEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, verbose_name='Enrolled At')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_teachers', to=settings.AUTH_USER_MODEL, verbose_name='Student')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_students', to=settings.AUTH_USER_MODEL, verbose_name='Teacher')),
            ],
            options={
                'verbose_name': 'Class Enrollment',
                'verbose_name_plural': 'Class Enrollments',
                'ordering': ['-enrolled_at'],
                'unique_together': {('teacher', 'student')},
            },
        ),
    ]
