# Generated by Django 4.2.30 on 2026-05-13 11:07

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='badges',
            field=models.JSONField(default=list, help_text='e.g. ["Reader Star", "Math Brave", "7-Day Streak"]', verbose_name='Badges'),
        ),
        migrations.AddField(
            model_name='user',
            name='class_grade',
            field=models.CharField(blank=True, choices=[('P1', 'Primary 1'), ('P2', 'Primary 2'), ('P3', 'Primary 3'), ('P4', 'Primary 4'), ('P5', 'Primary 5'), ('P6', 'Primary 6')], default='', help_text='The grade this teacher teaches, e.g. P6', max_length=5, verbose_name='Class Grade'),
        ),
        migrations.AddField(
            model_name='user',
            name='grade',
            field=models.CharField(blank=True, choices=[('P1', 'Primary 1'), ('P2', 'Primary 2'), ('P3', 'Primary 3'), ('P4', 'Primary 4'), ('P5', 'Primary 5'), ('P6', 'Primary 6')], default='', help_text='Student grade: P1–P6', max_length=5, verbose_name='Grade'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login_date',
            field=models.DateField(blank=True, help_text='Used to calculate and reset the streak', null=True, verbose_name='Last Login Date'),
        ),
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.IntegerField(default=1, help_text='Calculated from XP — levels up every 2500 XP', verbose_name='Level'),
        ),
        migrations.AddField(
            model_name='user',
            name='school',
            field=models.CharField(blank=True, choices=[('Riviera High School', 'Riviera High School'), ('Gashora Girls Academy of Science and Technology', 'Gashora Girls Academy of Science and Technology'), ('Green Hills Academy', 'Green Hills Academy'), ("FAWE Girls' School", "FAWE Girls' School"), ('Lycée de Kigali', 'Lycée de Kigali'), ('Agahozo-Shalom Youth Village', 'Agahozo-Shalom Youth Village'), ('White Dove Global School', 'White Dove Global School'), ('Nu-Vision High School', 'Nu-Vision High School'), ('Wellspring Academy', 'Wellspring Academy'), ('King David Academy', 'King David Academy'), ('ES Caf Muhese', 'ES Caf Muhese'), ('Groupe Scolaire Officiel de Butare', 'Groupe Scolaire Officiel de Butare'), ('Groupe Scolaire Sainte Bernadette de Save', 'Groupe Scolaire Sainte Bernadette de Save'), ('Collège du Christ-Roi', 'Collège du Christ-Roi'), ('Petit Séminaire Virgo Fidelis', 'Petit Séminaire Virgo Fidelis'), ('École des Sciences Byimana', 'École des Sciences Byimana'), ('Stella Matutina', 'Stella Matutina'), ('Sonrise High School', 'Sonrise High School'), ('Hope Haven Rwanda', 'Hope Haven Rwanda'), ('Kigali International Community School', 'Kigali International Community School')], default='', help_text='Selected from the list of Rwandan schools', max_length=255, verbose_name='School'),
        ),
        migrations.AddField(
            model_name='user',
            name='soma_id',
            field=models.CharField(default=users.models.generate_soma_id, help_text='Auto-generated login ID in format SOMA-XXXX-XXXX', max_length=20, unique=True, verbose_name='Soma ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='streak',
            field=models.IntegerField(default=0, help_text='Consecutive days the student has logged in', verbose_name='Login Streak (days)'),
        ),
        migrations.AddField(
            model_name='user',
            name='weak_subject',
            field=models.CharField(blank=True, default='', help_text='Subject needing most improvement — updated by progress tracking', max_length=100, verbose_name='Weak Subject'),
        ),
        migrations.AddField(
            model_name='user',
            name='xp',
            field=models.IntegerField(default=0, help_text='Earned through quizzes, homework, and activities', verbose_name='Experience Points'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_dyslexic',
            field=models.BooleanField(default=False, verbose_name='Has Dyslexia'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_premium',
            field=models.BooleanField(default=False, verbose_name='Premium Account'),
        ),
        migrations.AlterField(
            model_name='user',
            name='learning_style',
            field=models.CharField(blank=True, choices=[('visual', 'Visual'), ('auditory', 'Auditory'), ('reading', 'Reading'), ('kinesthetic', 'Kinesthetic')], max_length=20, null=True, verbose_name='Learning Style'),
        ),
        migrations.AlterField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(choices=[('kinyarwanda', 'Kinyarwanda'), ('english', 'English'), ('french', 'French'), ('swahili', 'Swahili')], default='english', max_length=20, verbose_name='Preferred Language'),
        ),
    ]
